services:
  - type: web
    name: abbey-backend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
